# Generated by Django 2.0.6 on 2018-06-06 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membre',
            options={'ordering': ('nom', 'prenom')},
        ),
        migrations.AlterUniqueTogether(
            name='membre',
            unique_together={('nom', 'prenom', 'date_de_naissance')},
        ),
    ]
