# Generated by Django 2.0.6 on 2018-06-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20180606_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
